name: Command via SSH

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
       key: ${{ secrets.SSH_PRIVATE_KEY }}
       known_hosts: unnecessary
    - run: whoami
